### ISSUE TITLE
if model_config["type"] == "yolov5":TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by monkeycc** [vietanhdev/anylabeling#121]
```
 anylabeling
Could not download https://huggingface.co/vietanhdev/segment-anything-onnx-models/resolve/main/sam_vit_h_4b8939.zip: <urlopen error [WinError 10054] 远程主机强迫关闭了一个现有的连接。>
Traceback (most recent call last):
  File "E:\anaconda3\envs\py38\lib\site-packages\anylabeling\utils.py", line 15, in run
    self.func(*self.args, **self.kwargs)
  File "E:\anaconda3\envs\py38\lib\site-packages\anylabeling\services\auto_labeling\model_manager.py", line 389, in _load_model
    if model_config["type"] == "yolov5":
TypeError: 'NoneType' object is not subscriptable
```

**Comment by vietanhdev** [comment]
@monkeycc Maybe your internet connection is not good to download the model.
You can try the following: download from a browser, extract, and load it as a custom model: <https://huggingface.co/vietanhdev/segment-anything-onnx-models/resolve/main/sam_vit_h_4b8939.zip>.

**Comment by Kk875** [comment]
> @monkeycc Maybe your internet connection is not good to download the model. You can try the following: download from a browser, extract, and load it as a custom model: https://huggingface.co/vietanhdev/segment-anything-onnx-models/resolve/main/sam_vit_h_4b8939.zip.
hi，Where should I put the model after I download it? My system is windows 11，thank you

**Comment by scottix** [comment]
Same issue as #160

**Comment by hustCYQ** [comment]
> > @monkeycc Maybe your internet connection is not good to download the model. You can try the following: download from a browser, extract, and load it as a custom model: https://huggingface.co/vietanhdev/segment-anything-onnx-models/resolve/main/sam_vit_h_4b8939.zip.
> > hi，Where should I put the model after I download it? My system is windows 11，thank you

Have you solved this problem? Can you share the detailed directory of file placement?

**Comment by vietanhdev** [comment]
This duplicate of #160 is fixed on current `main`. Commit 55338bf added the missing guard after model download, and the current download path now raises a clear `ValueError: Could not download model.` when a ZIP download returns no model directory instead of indexing `None`.

I reproduced the failed-download branch with `download_zip()` returning `None`; it exits through the handled error path and does not reach `model_config["type"]`. Closing as resolved.
