### ISSUE TITLE
anylabeling failed to execute script 'app' due to unhandled exception

### ISSUE THREAD

**Issue by simonnier** [vietanhdev/anylabeling#134]
Dear developer,

I encountered error dialog windows on windows 11 when double click AnyLabeling.exe. What is going on? How to fix this?

```
Traceback (most recent call last):
  File "app.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "views\mainwindow.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "views\labeling\label_wrapper.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "views\labeling\label_widget.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "imgviz\__init__.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "imgviz\_io\__init__.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "imgviz\_io\pyplot.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "matplotlib\__init__.py", line 991, in <module>
  File "matplotlib\__init__.py", line 639, in matplotlib_fname
  File "matplotlib\__init__.py", line 636, in gen_candidates
  File "matplotlib\__init__.py", line 335, in wrapper
  File "matplotlib\__init__.py", line 582, in get_configdir
  File "matplotlib\__init__.py", line 537, in _get_config_or_cache_dir
  File "pathlib.py", line 1181, in resolve
  File "pathlib.py", line 206, in resolve
OSError: [WinError 1] 函数不正确。: 'R:\\Temp\\tmpsij_08kp'
```

**Comment by vietanhdev** [comment]
Resolved by the current frozen build/toolchain. I reproduced the original non-default extraction layout by mapping an otherwise-unused `R:` drive, setting both `TEMP` and `TMP` to `R:\Temp`, and launching the exact v0.4.42 Windows CPU release artifact. PyInstaller created its `_MEI*` extraction directory there and the application remained healthy for 45 seconds. Closing as fixed; please reopen with a v0.4.42 traceback if the issue persists.
