### ISSUE TITLE
The program crashed when loading mobileSAM

### ISSUE THREAD

**Issue by YangWulve** [vietanhdev/anylabeling#160]
The progrgam crashed when loading mobileSAM for the first time. And will crash everytime after crashed.
Windows10, [AnyLabeling v0.3.3](https://github.com/vietanhdev/anylabeling/releases/tag/v0.3.3)。
![crashedMobileSAM](https://github.com/vietanhdev/anylabeling/assets/54839060/c0064ede-f736-4bff-b00d-2bf965be901e)

**Comment by scottix** [comment]
I was able to replicate.

1. Initial start loaded fine.
2. Secondary usage crashed.

```
Traceback (most recent call last):
  File "C:\Users\S\AppData\Local\Programs\Python\Python310\lib\site-packages\anylabeling\utils.py", line 15, in run
    self.func(*self.args, **self.kwargs)
  File "C:\Users\S\AppData\Local\Programs\Python\Python310\lib\site-packages\anylabeling\services\auto_labeling\model_manager.py", line 389, in _load_model
    if model_config["type"] == "yolov5":
TypeError: 'NoneType' object is not subscriptable
```
