### ISSUE TITLE
The software crashes when loading the model

### ISSUE THREAD

**Issue by lonelywanderer8** [vietanhdev/anylabeling#185]
I encountered a software crash while loading the SAM model.
Error message:
Traceback (most recent call last):
  File "D:\anaconda\envs\anylabelme\lib\site-packages\anylabeling\utils.py", line 15, in run
    self.func(*self.args, **self.kwargs)
  File "D:\anaconda\envs\anylabelme\lib\site-packages\anylabeling\services\auto_labeling\model_manager.py", line 438, in _load_model
    from .segment_anything import SegmentAnything
  File "D:\anaconda\envs\anylabelme\lib\site-packages\anylabeling\services\auto_labeling\segment_anything.py", line 20, in <module>
    from .sam2_onnx import SegmentAnything2ONNX
  File "D:\anaconda\envs\anylabelme\lib\site-packages\anylabeling\services\auto_labeling\sam2_onnx.py", line 11, in <module>
    class SegmentAnything2ONNX:
  File "D:\anaconda\envs\anylabelme\lib\site-packages\anylabeling\services\auto_labeling\sam2_onnx.py", line 20, in SegmentAnything2ONNX
    def encode(self, cv_image: np.ndarray) -> list[np.ndarray]:
TypeError: 'type' object is not subscriptable

**Comment by pinnintipraneethkumar** [comment]
which python version you are using? if you are using python 3.8 and earlier please upgarde to python3.9 or later and try.

**Comment by zhoujialos** [comment]
I also encountered a software crash while loading the SAM model.  My python version is python3.12

**Comment by chrish222** [comment]
Also application crash while loading the SAM model (tried 2 models, which are downloaded from huggingface). My Python version is 3.10.6  (win10).

**Comment by ainayves** [comment]
I also encountered this error on the EXE file. Any solution ?

**Comment by KlausikPL** [comment]
when you download exe crashes when loading model when you create env and you make pip install anylabeling anylabeling is sam 2 works normally probably exe is corrupted or something?

**Comment by vietanhdev** [comment]
The traceback in the original report is Python 3.8 evaluating `list[np.ndarray]`, which that Python version does not support. Current AnyLabeling releases require Python 3.11 or newer. I verified `sam2_onnx` imports on Python 3.11–3.13 in CI and in isolated Linux, macOS, and Windows environments.

The later comments do not include the same traceback and refer to old standalone releases. Please open a new issue with a current v0.4.37 traceback if a distinct model-loading problem remains.
