### ISSUE TITLE
Crashes on Ubuntu 24.04 

### ISSUE THREAD

**Issue by roboticsbrian** [vietanhdev/anylabeling#191]
`Anylabeling-Linux` crashes with the following:
```
Traceback (most recent call last):
  File "views/labeling/widgets/canvas.py", line 867, in paintEvent
TypeError: arguments did not match any overloaded call:
  fillRect(self, a0: QRectF, a1: Union[QBrush, Union[QColor, Qt.GlobalColor], QGradient]): argument 1 has unexpected type 'float'
  fillRect(self, a0: QRect, a1: Union[QBrush, Union[QColor, Qt.GlobalColor], QGradient]): argument 1 has unexpected type 'float'
  fillRect(self, x: int, y: int, w: int, h: int, b: Union[QBrush, Union[QColor, Qt.GlobalColor], QGradient]): argument 1 has unexpected type 'float'
  fillRect(self, a0: QRectF, color: Union[QColor, Qt.GlobalColor]): argument 1 has unexpected type 'float'
  fillRect(self, a0: QRect, color: Union[QColor, Qt.GlobalColor]): argument 1 has unexpected type 'float'
  fillRect(self, x: int, y: int, w: int, h: int, b: Union[QColor, Qt.GlobalColor]): argument 1 has unexpected type 'float'
  fillRect(self, x: int, y: int, w: int, h: int, c: Qt.GlobalColor): argument 1 has unexpected type 'float'
  fillRect(self, r: QRect, c: Qt.GlobalColor): argument 1 has unexpected type 'float'
  fillRect(self, r: QRectF, c: Qt.GlobalColor): argument 1 has unexpected type 'float'
  fillRect(self, x: int, y: int, w: int, h: int, style: Qt.BrushStyle): argument 1 has unexpected type 'float'
  fillRect(self, r: QRect, style: Qt.BrushStyle): argument 1 has unexpected type 'float'
  fillRect(self, r: QRectF, style: Qt.BrushStyle): argument 1 has unexpected type 'float'
  fillRect(self, x: int, y: int, w: int, h: int, preset: QGradient.Preset): argument 1 has unexpected type 'float'
  fillRect(self, r: QRect, preset: QGradient.Preset): argument 1 has unexpected type 'float'
  fillRect(self, r: QRectF, preset: QGradient.Preset): argument 1 has unexpected type 'float'
Aborted (core dumped)
```

`Anylabeling-Linux-GPU` crashes with the following:
```
Traceback (most recent call last):
  File "views/labeling/widgets/canvas.py", line 867, in paintEvent
TypeError: arguments did not match any overloaded call:
  fillRect(self, a0: QRectF, a1: Union[QBrush, Union[QColor, Qt.GlobalColor], QGradient]): argument 1 has unexpected type 'float'
  fillRect(self, a0: QRect, a1: Union[QBrush, Union[QColor, Qt.GlobalColor], QGradient]): argument 1 has unexpected type 'float'
  fillRect(self, x: int, y: int, w: int, h: int, b: Union[QBrush, Union[QColor, Qt.GlobalColor], QGradient]): argument 1 has unexpected type 'float'
  fillRect(self, a0: QRectF, color: Union[QColor, Qt.GlobalColor]): argument 1 has unexpected type 'float'
  fillRect(self, a0: QRect, color: Union[QColor, Qt.GlobalColor]): argument 1 has unexpected type 'float'
  fillRect(self, x: int, y: int, w: int, h: int, b: Union[QColor, Qt.GlobalColor]): argument 1 has unexpected type 'float'
  fillRect(self, x: int, y: int, w: int, h: int, c: Qt.GlobalColor): argument 1 has unexpected type 'float'
  fillRect(self, r: QRect, c: Qt.GlobalColor): argument 1 has unexpected type 'float'
  fillRect(self, r: QRectF, c: Qt.GlobalColor): argument 1 has unexpected type 'float'
  fillRect(self, x: int, y: int, w: int, h: int, style: Qt.BrushStyle): argument 1 has unexpected type 'float'
  fillRect(self, r: QRect, style: Qt.BrushStyle): argument 1 has unexpected type 'float'
  fillRect(self, r: QRectF, style: Qt.BrushStyle): argument 1 has unexpected type 'float'
  fillRect(self, x: int, y: int, w: int, h: int, preset: QGradient.Preset): argument 1 has unexpected type 'float'
  fillRect(self, r: QRect, preset: QGradient.Preset): argument 1 has unexpected type 'float'
  fillRect(self, r: QRectF, preset: QGradient.Preset): argument 1 has unexpected type 'float'
Aborted (core dumped)
```

`anylabeling` installed via `pip` crashes with:
```
Traceback (most recent call last):
  File "/home/brian/miniforge3/envs/anylabeling/lib/python3.11/site-packages/anylabeling/views/labeling/widgets/canvas.py", line 867, in paintEvent
    p.fillRect(
TypeError: arguments did not match any overloaded call:
  fillRect(self, QRectF, Union[QBrush, QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'
  fillRect(self, QRect, Union[QBrush, QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'
  fillRect(self, int, int, int, int, Union[QBrush, QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'
  fillRect(self, QRectF, Union[QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'
  fillRect(self, QRect, Union[QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'
  fillRect(self, int, int, int, int, Union[QColor, Qt.GlobalColor, QGradient]): argument 1 has unexpected type 'float'
  fillRect(self, int, int, int, int, Qt.GlobalColor): argument 1 has unexpected type 'float'
  fillRect(self, QRect, Qt.GlobalColor): argument 1 has unexpected type 'float'
  fillRect(self, QRectF, Qt.GlobalColor): argument 1 has unexpected type 'float'
  fillRect(self, int, int, int, int, Qt.BrushStyle): argument 1 has unexpected type 'float'
  fillRect(self, QRect, Qt.BrushStyle): argument 1 has unexpected type 'float'
  fillRect(self, QRectF, Qt.BrushStyle): argument 1 has unexpected type 'float'
  fillRect(self, int, int, int, int, QGradient.Preset): argument 1 has unexpected type 'float'
  fillRect(self, QRect, QGradient.Preset): argument 1 has unexpected type 'float'
  fillRect(self, QRectF, QGradient.Preset): argument 1 has unexpected type 'float'
Aborted (core dumped)
```

**Comment by vietanhdev** [comment]
The reported QPainter.fillRect crash was fixed by commit 0ba7232, which converts the floating-point text coordinates to integers before calling the Qt overload (and likewise fixes drawText). I manually rendered a labeled shape with fractional coordinates using the current PyQt6 canvas and confirmed it completes successfully. Closing as completed.
