### ISSUE TITLE
The program crashed while downloading the model.

### ISSUE THREAD

**Issue by KroitAax** [vietanhdev/anylabeling#52]
The program crashed while downloading the model.

**Comment by vietanhdev** [comment]
Please specify:
- Your OS (Win, Mac,...)
- Your AnyLabeling version
- Your internet speed at: https://www.speedtest.net/
Thank you!

**Comment by Rane2021** [comment]
my machine is macos 12.6.5 with m1 chip.  load model error is:

Traceback (most recent call last):
  File "urllib/request.py", line 1350, in do_open
  File "http/client.py", line 1281, in request
  File "http/client.py", line 1327, in _send_request
  File "http/client.py", line 1276, in endheaders
  File "http/client.py", line 1036, in _send_output
  File "http/client.py", line 976, in send
  File "http/client.py", line 1451, in connect
  File "ssl.py", line 423, in wrap_socket
  File "ssl.py", line 870, in _create
  File "ssl.py", line 1139, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "services/auto_labeling/model.py", line 124, in get_model_abs_path
  File "urllib/request.py", line 247, in urlretrieve
  File "urllib/request.py", line 222, in urlopen
  File "urllib/request.py", line 525, in open
  File "urllib/request.py", line 543, in _open
  File "urllib/request.py", line 503, in _call_chain
  File "urllib/request.py", line 1393, in https_open
  File "urllib/request.py", line 1352, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "utils.py", line 15, in run
  File "services/auto_labeling/model_manager.py", line 149, in _load_model
  File "services/auto_labeling/segment_anything.py", line 52, in __init__
  File "services/auto_labeling/model.py", line 130, in get_model_abs_path
Exception: Could not download model from https://github.com/vietanhdev/anylabeling-assets/releases/download/v0.2.0/segment_anything_vit_b_encoder_quant.onnx: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)>
[1]    99692 abort      ./anylabeling

**Comment by Rane2021** [comment]
it see like: network error, is there any ways to download model and put it in a folder

**Comment by susigo** [comment]
i face the same problem!

**Comment by vietanhdev** [comment]
Please check [AnyLabeling v0.2.16](https://github.com/vietanhdev/anylabeling/releases/tag/v0.2.16) to see if the error still persists.

**Comment by vietanhdev** [comment]
From AnyLabeling v0.2.22, to load custom models:
- Download models from [here](https://github.com/vietanhdev/anylabeling-assets/releases/tag/v0.4.0), extract.
- Load the models with **Custom Models** feature: https://anylabeling.com/docs/custom-models.
