### ISSUE TITLE
Crash when loading SAM Model

### ISSUE THREAD

**Issue by dhunjoshi** [vietanhdev/anylabeling#70]
Using GTX1650 GPU.

Traceback (most recent call last):
  File "D:\anaconda3\envs\anylabeling\lib\site-packages\anylabeling\utils.py", line 15, in run
    self.func(*self.args, **self.kwargs)
  File "D:\anaconda3\envs\anylabeling\lib\site-packages\anylabeling\services\auto_labeling\model_manager.py", line 151, in _load_model
    model_info["model"] = SegmentAnything(
  File "D:\anaconda3\envs\anylabeling\lib\site-packages\anylabeling\services\auto_labeling\segment_anything.py", line 74, in __init__
    self.encoder_session = onnxruntime.InferenceSession(
  File "D:\anaconda3\envs\anylabeling\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 360, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "D:\anaconda3\envs\anylabeling\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 408, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1106 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "D:\anaconda3\envs\anylabeling\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"

**Comment by web-ho** [comment]
Try reinstalling, as mentioned you are using GPU. So, check if you are installing the correct requirements.txt.

If the error didn't resolve check if the specified .dll file is present. Can also look for more info [here](https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order#standard-search-order-for-desktop-applications)

**Comment by vietanhdev** [comment]
@dhunjoshi Please try the latest version:

- For CPU version:
```
pip install -U anylabeling
```
- For GPU version:
```
pip install -U anylabeling-gpu
```
Thank you!

**Comment by vietanhdev** [comment]
Documentation for GPU support: https://anylabeling.com/docs/gpu.

**Comment by vietanhdev** [comment]
From AnyLabeling v0.2.22, to load custom models:
- Download models from [here](https://github.com/vietanhdev/anylabeling-assets/releases/tag/v0.4.0), extract.
- Load the models with **Custom Models** feature: https://anylabeling.com/docs/custom-models.
