### ISSUE TITLE
Protobuf parsing failed

### ISSUE THREAD

**Issue by aliddp** [vietanhdev/anylabeling#9]
Hi, thank you for your great work I get this error when I try auto labeling
Traceback (most recent call last):
  File "E:\Anaconda\envs\cubercnn\lib\site-packages\anylabeling\utils.py", line 15, in run
    self.func(*self.args, **self.kwargs)
  File "E:\Anaconda\envs\cubercnn\lib\site-packages\anylabeling\services\auto_labeling\model_manager.py", line 118, in _load_model
    model_info["model"] = SegmentAnything(
  File "E:\Anaconda\envs\cubercnn\lib\site-packages\anylabeling\services\auto_labeling\segment_anything.py", line 57, in __init__
    self.encoder_session = onnxruntime.InferenceSession(
  File "E:\Anaconda\envs\cubercnn\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 360, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "E:\Anaconda\envs\cubercnn\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 397, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from C:\Users\user\data\models\segment_anything\vit_b-encoder-quant.onnx failed:Protobuf parsing failed.

**Comment by vietanhdev** [comment]
Please check again. I have restore files.

**Comment by aliddp** [comment]
> Please check again. I have restore files.

I was able to download assets directly and past them in their corresponding folder but not through the GUI

**Comment by vietanhdev** [comment]
> > Please check again. I have restore files.
> 
> I was able to download assets directly and past them in their corresponding folder but not through the GUI

Please try with the latest version. This issue was fixed. Thanks.
