### ISSUE TITLE
 QPoint(QPoint): argument 1 has unexpected type 'float'

### ISSUE THREAD

**Issue by monkeycc** [vietanhdev/anylabeling#96]
```
Traceback (most recent call last):
  File "C:\Users\monke\anaconda3\lib\site-packages\anylabeling\views\labeling\widgets\canvas.py", line 285, in mouseMoveEvent
    pos = self.intersection_point(self.current[-1], pos)
  File "C:\Users\monke\anaconda3\lib\site-packages\anylabeling\views\labeling\widgets\canvas.py", line 1043, in intersection_point
    return QtCore.QPoint(x, y)
TypeError: arguments did not match any overloaded call:
  QPoint(): too many arguments
  QPoint(int, int): argument 1 has unexpected type 'float'
  QPoint(QPoint): argument 1 has unexpected type 'float'
```

**Comment by vietanhdev** [comment]
@monkeycc Resolved in #101 . Please check and feedback.
Thank you very much!
